apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::388626296320:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::388626296320:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EWKE8UZWQW1
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-18T00:59:48Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-18T00:59:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-03-18T01:16:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4342"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4a2fd2d7-ebee-419a-84fa-47d3759a5fb7
